HEXAGRAM_PROFILES = {
    "111111": {
        "number": 1,
        "name_en": "The Creative",
        "name_zh": "乾",
        "theme": "initiative",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Heaven",
        "trigram_lower": "Heaven",
        "short_meaning": "Strong creative force and leadership."
    },
    "000000": {
        "number": 2,
        "name_en": "The Receptive",
        "name_zh": "坤",
        "theme": "receptivity",
        "energy_level": "low",
        "action_type": "wait",
        "trigram_upper": "Earth",
        "trigram_lower": "Earth",
        "short_meaning": "Nurturing, yielding, and grounded support."
    },
    "100010": {
        "number": 3,
        "name_en": "Difficulty at the Beginning",
        "name_zh": "屯",
        "theme": "growth",
        "energy_level": "mid",
        "action_type": "wait",
        "trigram_upper": "Water",
        "trigram_lower": "Thunder",
        "short_meaning": "Difficulty at the beginning; potential for growth."
    },
    "010001": {
        "number": 4,
        "name_en": "Youthful Folly",
        "name_zh": "蒙",
        "theme": "education",
        "energy_level": "low",
        "action_type": "reflect",
        "trigram_upper": "Mountain",
        "trigram_lower": "Water",
        "short_meaning": "Inexperience; need for guidance and learning."
    },
    "111010": {
        "number": 5,
        "name_en": "Waiting",
        "name_zh": "需",
        "theme": "patience",
        "energy_level": "mid",
        "action_type": "wait",
        "trigram_upper": "Water",
        "trigram_lower": "Heaven",
        "short_meaning": "Calculated waiting for the right moment."
    },
    "010111": {
        "number": 6,
        "name_en": "Conflict",
        "name_zh": "訟",
        "theme": "caution",
        "energy_level": "mid",
        "action_type": "retreat",
        "trigram_upper": "Heaven",
        "trigram_lower": "Water",
        "short_meaning": "Conflict; seek mediation and avoid escalation."
    },
    "010000": {
        "number": 7,
        "name_en": "The Army",
        "name_zh": "師",
        "theme": "discipline",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Earth",
        "trigram_lower": "Water",
        "short_meaning": "Organization and leadership in challenging times."
    },
    "000010": {
        "number": 8,
        "name_en": "Holding Together",
        "name_zh": "比",
        "theme": "unity",
        "energy_level": "mid",
        "action_type": "connect",
        "trigram_upper": "Water",
        "trigram_lower": "Earth",
        "short_meaning": "Strength in alliance and mutual support."
    },
    "111011": {
        "number": 9,
        "name_en": "Small Taming",
        "name_zh": "小畜",
        "theme": "restraint",
        "energy_level": "mid",
        "action_type": "reflect",
        "trigram_upper": "Wind",
        "trigram_lower": "Heaven",
        "short_meaning": "Small influences; prepare for future action."
    },
    "110111": {
        "number": 10,
        "name_en": "Treading",
        "name_zh": "履",
        "theme": "conduct",
        "energy_level": "mid",
        "action_type": "act",
        "trigram_upper": "Heaven",
        "trigram_lower": "Lake",
        "short_meaning": "Proceeding with caution and proper etiquette."
    },
    "111000": {
        "number": 11,
        "name_en": "Peace",
        "name_zh": "泰",
        "theme": "harmony",
        "energy_level": "high",
        "action_type": "connect",
        "trigram_upper": "Earth",
        "trigram_lower": "Heaven",
        "short_meaning": "Prosperity and balance between heaven and earth."
    },
    "000111": {
        "number": 12,
        "name_en": "Standstill",
        "name_zh": "否",
        "theme": "stagnation",
        "energy_level": "low",
        "action_type": "retreat",
        "trigram_upper": "Heaven",
        "trigram_lower": "Earth",
        "short_meaning": "Obstruction; withdrawal is necessary."
    },
    "101111": {
        "number": 13,
        "name_en": "Fellowship",
        "name_zh": "同人",
        "theme": "fellowship",
        "energy_level": "high",
        "action_type": "connect",
        "trigram_upper": "Heaven",
        "trigram_lower": "Fire",
        "short_meaning": "Community and shared goals among people."
    },
    "111101": {
        "number": 14,
        "name_en": "Great Possession",
        "name_zh": "大有",
        "theme": "abundance",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Fire",
        "trigram_lower": "Heaven",
        "short_meaning": "Great success and wealth through virtue."
    },
    "001000": {
        "number": 15,
        "name_en": "Modesty",
        "name_zh": "謙",
        "theme": "modesty",
        "energy_level": "mid",
        "action_type": "reflect",
        "trigram_upper": "Earth",
        "trigram_lower": "Mountain",
        "short_meaning": "Success through humility and balance."
    },
    "000100": {
        "number": 16,
        "name_en": "Enthusiasm",
        "name_zh": "豫",
        "theme": "enthusiasm",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Thunder",
        "trigram_lower": "Earth",
        "short_meaning": "Inspiration and movement through joy."
    },
    "100110": {
        "number": 17,
        "name_en": "Following",
        "name_zh": "隨",
        "theme": "adaptation",
        "energy_level": "mid",
        "action_type": "wait",
        "trigram_upper": "Lake",
        "trigram_lower": "Thunder",
        "short_meaning": "Yielding to the situation to achieve success."
    },
    "011001": {
        "number": 18,
        "name_en": "Work on What Has Been Spoiled",
        "name_zh": "蠱",
        "theme": "repair",
        "energy_level": "mid",
        "action_type": "act",
        "trigram_upper": "Mountain",
        "trigram_lower": "Wind",
        "short_meaning": "Correcting errors and restoring order."
    },
    "110000": {
        "number": 19,
        "name_en": "Approach",
        "name_zh": "臨",
        "theme": "advancement",
        "energy_level": "mid",
        "action_type": "act",
        "trigram_upper": "Earth",
        "trigram_lower": "Lake",
        "short_meaning": "Growth and progress; vigilance is needed."
    },
    "000011": {
        "number": 20,
        "name_en": "Contemplation",
        "name_zh": "觀",
        "theme": "contemplation",
        "energy_level": "low",
        "action_type": "reflect",
        "trigram_upper": "Wind",
        "trigram_lower": "Earth",
        "short_meaning": "Observing and understanding the situation."
    },
    "100101": {
        "number": 21,
        "name_en": "Biting Through",
        "name_zh": "噬嗑",
        "theme": "resolution",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Fire",
        "trigram_lower": "Thunder",
        "short_meaning": "Biting through obstacles with justice."
    },
    "101001": {
        "number": 22,
        "name_en": "Grace",
        "name_zh": "賁",
        "theme": "aesthetics",
        "energy_level": "mid",
        "action_type": "reflect",
        "trigram_upper": "Mountain",
        "trigram_lower": "Fire",
        "short_meaning": "Grace and elegance; focus on appearance."
    },
    "000001": {
        "number": 23,
        "name_en": "Splitting Apart",
        "name_zh": "剝",
        "theme": "deterioration",
        "energy_level": "low",
        "action_type": "retreat",
        "trigram_upper": "Mountain",
        "trigram_lower": "Earth",
        "short_meaning": "Splitting apart; endure through stillness."
    },
    "100000": {
        "number": 24,
        "name_en": "Return",
        "name_zh": "復",
        "theme": "renewal",
        "energy_level": "low",
        "action_type": "wait",
        "trigram_upper": "Earth",
        "trigram_lower": "Thunder",
        "short_meaning": "Return to the source; start of a new cycle."
    },
    "100111": {
        "number": 25,
        "name_en": "Innocence",
        "name_zh": "無妄",
        "theme": "innocence",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Heaven",
        "trigram_lower": "Thunder",
        "short_meaning": "Acting without ulterior motives; spontaneity."
    },
    "111001": {
        "number": 26,
        "name_en": "Great Taming",
        "name_zh": "大畜",
        "theme": "stability",
        "energy_level": "high",
        "action_type": "reflect",
        "trigram_upper": "Mountain",
        "trigram_lower": "Heaven",
        "short_meaning": "Accumulating power and holding steady."
    },
    "100001": {
        "number": 27,
        "name_en": "Nourishment",
        "name_zh": "頤",
        "theme": "nourishment",
        "energy_level": "mid",
        "action_type": "reflect",
        "trigram_upper": "Mountain",
        "trigram_lower": "Thunder",
        "short_meaning": "Providing sustenance for self and others."
    },
    "011110": {
        "number": 28,
        "name_en": "Preponderance of the Great",
        "name_zh": "大過",
        "theme": "crisis",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Lake",
        "trigram_lower": "Wind",
        "short_meaning": "Critical transition; extraordinary action needed."
    },
    "010010": {
        "number": 29,
        "name_en": "The Abysmal Water",
        "name_zh": "坎",
        "theme": "danger",
        "energy_level": "mid",
        "action_type": "wait",
        "trigram_upper": "Water",
        "trigram_lower": "Water",
        "short_meaning": "Navigating risks with sincerity and depth."
    },
    "101101": {
        "number": 30,
        "name_en": "The Clinging Fire",
        "name_zh": "離",
        "theme": "clarity",
        "energy_level": "high",
        "action_type": "reflect",
        "trigram_upper": "Fire",
        "trigram_lower": "Fire",
        "short_meaning": "Insight and dependence on the light."
    },
    "001110": {
        "number": 31,
        "name_en": "Influence",
        "name_zh": "咸",
        "theme": "influence",
        "energy_level": "mid",
        "action_type": "connect",
        "trigram_upper": "Lake",
        "trigram_lower": "Mountain",
        "short_meaning": "Mutual attraction and emotional resonance."
    },
    "011100": {
        "number": 32,
        "name_en": "Duration",
        "name_zh": "恆",
        "theme": "continuity",
        "energy_level": "mid",
        "action_type": "wait",
        "trigram_upper": "Thunder",
        "trigram_lower": "Wind",
        "short_meaning": "Enduring through consistency and habit."
    },
    "001111": {
        "number": 33,
        "name_en": "Retreat",
        "name_zh": "遁",
        "theme": "withdrawal",
        "energy_level": "mid",
        "action_type": "retreat",
        "trigram_upper": "Heaven",
        "trigram_lower": "Mountain",
        "short_meaning": "Strategic retreat to preserve strength."
    },
    "111100": {
        "number": 34,
        "name_en": "Great Power",
        "name_zh": "大壯",
        "theme": "power",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Thunder",
        "trigram_lower": "Heaven",
        "short_meaning": "Great strength; use with caution and justice."
    },
    "000101": {
        "number": 35,
        "name_en": "Progress",
        "name_zh": "晉",
        "theme": "progress",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Fire",
        "trigram_lower": "Earth",
        "short_meaning": "Steady advancement and recognition."
    },
    "101000": {
        "number": 36,
        "name_en": "Darkening of the Light",
        "name_zh": "明夷",
        "theme": "obscurity",
        "energy_level": "low",
        "action_type": "retreat",
        "trigram_upper": "Earth",
        "trigram_lower": "Fire",
        "short_meaning": "Hiding your light in dark times."
    },
    "101011": {
        "number": 37,
        "name_en": "The Family",
        "name_zh": "家人",
        "theme": "family",
        "energy_level": "mid",
        "action_type": "connect",
        "trigram_upper": "Wind",
        "trigram_lower": "Fire",
        "short_meaning": "Maintaining order and harmony within the home."
    },
    "110101": {
        "number": 38,
        "name_en": "Opposition",
        "name_zh": "睽",
        "theme": "opposition",
        "energy_level": "mid",
        "action_type": "reflect",
        "trigram_upper": "Fire",
        "trigram_lower": "Lake",
        "short_meaning": "Reconciling differences in perspective."
    },
    "001010": {
        "number": 39,
        "name_en": "Obstruction",
        "name_zh": "蹇",
        "theme": "hardship",
        "energy_level": "low",
        "action_type": "retreat",
        "trigram_upper": "Water",
        "trigram_lower": "Mountain",
        "short_meaning": "Obstacles; stop and seek help."
    },
    "010100": {
        "number": 40,
        "name_en": "Deliverance",
        "name_zh": "解",
        "theme": "liberation",
        "energy_level": "mid",
        "action_type": "act",
        "trigram_upper": "Thunder",
        "trigram_lower": "Water",
        "short_meaning": "Release of tension and resolution of problems."
    },
    "110001": {
        "number": 41,
        "name_en": "Decrease",
        "name_zh": "損",
        "theme": "reduction",
        "energy_level": "low",
        "action_type": "reflect",
        "trigram_upper": "Mountain",
        "trigram_lower": "Lake",
        "short_meaning": "Simplifying and letting go for future gain."
    },
    "100011": {
        "number": 42,
        "name_en": "Increase",
        "name_zh": "益",
        "theme": "increase",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Wind",
        "trigram_lower": "Thunder",
        "short_meaning": "Expansion and benefit for the community."
    },
    "111110": {
        "number": 43,
        "name_en": "Breakthrough",
        "name_zh": "夬",
        "theme": "breakthrough",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Lake",
        "trigram_lower": "Heaven",
        "short_meaning": "Decisive action to eliminate negativity."
    },
    "011111": {
        "number": 44,
        "name_en": "Coming to Meet",
        "name_zh": "姤",
        "theme": "temptation",
        "energy_level": "mid",
        "action_type": "wait",
        "trigram_upper": "Heaven",
        "trigram_lower": "Wind",
        "short_meaning": "Sudden encounters; beware of weak influences."
    },
    "000110": {
        "number": 45,
        "name_en": "Gathering Together",
        "name_zh": "萃",
        "theme": "gathering",
        "energy_level": "mid",
        "action_type": "connect",
        "trigram_upper": "Lake",
        "trigram_lower": "Earth",
        "short_meaning": "Coming together for a common purpose."
    },
    "011000": {
        "number": 46,
        "name_en": "Pushing Upward",
        "name_zh": "升",
        "theme": "ascent",
        "energy_level": "mid",
        "action_type": "act",
        "trigram_upper": "Earth",
        "trigram_lower": "Wind",
        "short_meaning": "Steady upward movement through effort."
    },
    "010110": {
        "number": 47,
        "name_en": "Oppression",
        "name_zh": "困",
        "theme": "exhaustion",
        "energy_level": "low",
        "action_type": "reflect",
        "trigram_upper": "Lake",
        "trigram_lower": "Water",
        "short_meaning": "Adversity; maintain inner strength and silence."
    },
    "011010": {
        "number": 48,
        "name_en": "The Well",
        "name_zh": "井",
        "theme": "source",
        "energy_level": "mid",
        "action_type": "reflect",
        "trigram_upper": "Water",
        "trigram_lower": "Wind",
        "short_meaning": "The well; unchanging source of nourishment."
    },
    "101110": {
        "number": 49,
        "name_en": "Revolution",
        "name_zh": "革",
        "theme": "transformation",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Lake",
        "trigram_lower": "Fire",
        "short_meaning": "Radical change and necessary revolution."
    },
    "011101": {
        "number": 50,
        "name_en": "The Cauldron",
        "name_zh": "鼎",
        "theme": "refinement",
        "energy_level": "high",
        "action_type": "reflect",
        "trigram_upper": "Fire",
        "trigram_lower": "Wind",
        "short_meaning": "Transformation through spiritual values."
    },
    "100100": {
        "number": 51,
        "name_en": "The Arousing Thunder",
        "name_zh": "震",
        "theme": "awakening",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Thunder",
        "trigram_lower": "Thunder",
        "short_meaning": "Sudden shock leading to introspection."
    },
    "001001": {
        "number": 52,
        "name_en": "Keeping Still Mountain",
        "name_zh": "艮",
        "theme": "stillness",
        "energy_level": "low",
        "action_type": "reflect",
        "trigram_upper": "Mountain",
        "trigram_lower": "Mountain",
        "short_meaning": "Resting and quieting the mind."
    },
    "001011": {
        "number": 53,
        "name_en": "Development",
        "name_zh": "漸",
        "theme": "development",
        "energy_level": "mid",
        "action_type": "wait",
        "trigram_upper": "Wind",
        "trigram_lower": "Mountain",
        "short_meaning": "Gradual and steady progress over time."
    },
    "110100": {
        "number": 54,
        "name_en": "The Marrying Maiden",
        "name_zh": "歸妹",
        "theme": "impulsiveness",
        "energy_level": "mid",
        "action_type": "wait",
        "trigram_upper": "Thunder",
        "trigram_lower": "Lake",
        "short_meaning": "Improper relationships or premature action."
    },
    "101100": {
        "number": 55,
        "name_en": "Abundance",
        "name_zh": "豐",
        "theme": "abundance",
        "energy_level": "high",
        "action_type": "act",
        "trigram_upper": "Thunder",
        "trigram_lower": "Fire",
        "short_meaning": "Peak achievement; share the prosperity."
    },
    "001101": {
        "number": 56,
        "name_en": "The Wanderer",
        "name_zh": "旅",
        "theme": "transition",
        "energy_level": "low",
        "action_type": "retreat",
        "trigram_upper": "Fire",
        "trigram_lower": "Mountain",
        "short_meaning": "Traveling through life with detachment."
    },
    "011011": {
        "number": 57,
        "name_en": "The Gentle Wind",
        "name_zh": "巽",
        "theme": "penetration",
        "energy_level": "mid",
        "action_type": "reflect",
        "trigram_upper": "Wind",
        "trigram_lower": "Wind",
        "short_meaning": "Subtle influence and persistent effort."
    },
    "110110": {
        "number": 58,
        "name_en": "The Joyous Lake",
        "name_zh": "兌",
        "theme": "joy",
        "energy_level": "high",
        "action_type": "connect",
        "trigram_upper": "Lake",
        "trigram_lower": "Lake",
        "short_meaning": "Open communication and shared happiness."
    },
    "010011": {
        "number": 59,
        "name_en": "Dispersion",
        "name_zh": "渙",
        "theme": "dissolution",
        "energy_level": "mid",
        "action_type": "connect",
        "trigram_upper": "Wind",
        "trigram_lower": "Water",
        "short_meaning": "Breaking through barriers and spreading out."
    },
    "110010": {
        "number": 60,
        "name_en": "Limitation",
        "name_zh": "節",
        "theme": "limitation",
        "energy_level": "mid",
        "action_type": "reflect",
        "trigram_upper": "Water",
        "trigram_lower": "Lake",
        "short_meaning": "Setting boundaries to ensure success."
    },
    "110011": {
        "number": 61,
        "name_en": "Inner Truth",
        "name_zh": "中孚",
        "theme": "sincerity",
        "energy_level": "mid",
        "action_type": "connect",
        "trigram_upper": "Wind",
        "trigram_lower": "Lake",
        "short_meaning": "Inner truth and rapport with others."
    },
    "001100": {
        "number": 62,
        "name_en": "Preponderance of the Small",
        "name_zh": "小過",
        "theme": "caution",
        "energy_level": "low",
        "action_type": "reflect",
        "trigram_upper": "Thunder",
        "trigram_lower": "Mountain",
        "short_meaning": "Attending to small details; avoid great risks."
    },
    "101010": {
        "number": 63,
        "name_en": "After Completion",
        "name_zh": "既濟",
        "theme": "completion",
        "energy_level": "high",
        "action_type": "wait",
        "trigram_upper": "Water",
        "trigram_lower": "Fire",
        "short_meaning": "Order achieved; beware of eventual decline."
    },
    "010101": {
        "number": 64,
        "name_en": "Before Completion",
        "name_zh": "未濟",
        "theme": "potential",
        "energy_level": "mid",
        "action_type": "act",
        "trigram_upper": "Fire",
        "trigram_lower": "Water",
        "short_meaning": "Transition phase before a new beginning."
    }
}
